[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path = 'cache_forge'
fs_permissions = [{ access = "read", path = "./config.json" }]

[rpc_endpoints]
opt-goerli = "https://opt-sepolia.g.alchemy.com/v2/${OP_ALCHEMY_API_KEY}"
base-sepolia = "https://base-sepolia.g.alchemy.com/v2/${BASE_ALCHEMY_API_KEY}"
